name: CI

on:
  - push
  - pull_request

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -x -i SC2086
        with:
          # NOTE: Use just multiple-line format, not YAML's block styles. This
          # value is considered a whitespace-separated string. This action
          # merely embeds this value into words of the 'for' control statement
          # to ignore paths, so multiple line strings probably break
          # shellscript's syntax.
          ignore_paths:
            accept/lib
            ignore
